<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("");
$APPLICATION->SetTitle("") ?><?php

$APPLICATION->SetTitle("Оформление заказа");

?>


<div class="custom-basket-top">
    <?$APPLICATION->IncludeComponent(
        "bitrix:sale.basket.basket",
        "template.1",
        Array(
            "ACTION_VARIABLE" => "basketAction",
            "ADDITIONAL_PICT_PROP_13" => "-",
            "AUTO_CALCULATION" => "Y",
            "BASKET_IMAGES_SCALING" => "adaptive",
            "COLUMNS_LIST_EXT" => array("PREVIEW_PICTURE","DISCOUNT","DELETE","DELAY","TYPE","SUM"),
            "COLUMNS_LIST_MOBILE" => array("PREVIEW_PICTURE","DISCOUNT","DELETE","DELAY","TYPE","SUM"),
            "COMPATIBLE_MODE" => "Y",
            "CORRECT_RATIO" => "Y",
            "DEFERRED_REFRESH" => "N",
            "DISCOUNT_PERCENT_POSITION" => "bottom-right",
            "DISPLAY_MODE" => "extended",
            "EMPTY_BASKET_HINT_PATH" => "/",
            "GIFTS_BLOCK_TITLE" => "Выберите один из подарков",
            "GIFTS_COLUMNS" => "4",
            "GIFTS_CONVERT_CURRENCY" => "N",
            "GIFTS_HIDE_BLOCK_TITLE" => "N",
            "GIFTS_HIDE_NOT_AVAILABLE" => "N",
            "GIFTS_MESS_BTN_BUY" => "Выбрать",
            "GIFTS_MESS_BTN_DETAIL" => "Подробнее",
            "GIFTS_PAGE_ELEMENT_COUNT" => "4",
            "GIFTS_PLACE" => "BOTTOM",
            "GIFTS_PRODUCT_PROPS_VARIABLE" => "prop",
            "GIFTS_PRODUCT_QUANTITY_VARIABLE" => "quantity",
            "GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
            "GIFTS_SHOW_OLD_PRICE" => "N",
            "GIFTS_TEXT_LABEL_GIFT" => "Подарок",
            "HIDE_COUPON" => "N",
            "LABEL_PROP" => array(),
            "ORDER_FAST_USE" => "N",
            "PATH_TO_ORDER" => "/personal/order/make/",
            "PRICE_DISPLAY_MODE" => "Y",
            "PRICE_VAT_SHOW_VALUE" => "N",
            "PRODUCT_BLOCKS_ORDER" => "props,sku,columns",
            "QUANTITY_FLOAT" => "Y",
            "SET_TITLE" => "Y",
            "SHOW_DISCOUNT_PERCENT" => "Y",
            "SHOW_FILTER" => "Y",
            "SHOW_RESTORE" => "Y",
            "TEMPLATE_THEME" => "blue",
            "TOTAL_BLOCK_DISPLAY" => array("top"),
            "USE_DYNAMIC_SCROLL" => "Y",
            "USE_ENHANCED_ECOMMERCE" => "N",
            "USE_GIFTS" => "Y",
            "USE_PREPAYMENT" => "N",
            "USE_PRICE_ANIMATION" => "Y"
        )
    );?>
</div>


<?$APPLICATION->IncludeComponent(
	"bitrix:sale.order.ajax",
	"simple.1",
	Array(
		"ACTION_VARIABLE" => "action",
		"ADDITIONAL_PICT_PROP_12" => "-",
		"ADDITIONAL_PICT_PROP_13" => "-",
		"ADDITIONAL_PICT_PROP_16" => "-",
		"ADDITIONAL_PICT_PROP_20" => "-",
		"ADDITIONAL_PICT_PROP_21" => "-",
		"ADDITIONAL_PICT_PROP_31" => "-",
		"ADDITIONAL_PICT_PROP_4" => "-",
		"ADDITIONAL_PICT_PROP_43" => "-",
		"ADDITIONAL_PICT_PROP_44" => "-",
		"ADDITIONAL_PICT_PROP_5" => "-",
		"ADDITIONAL_PICT_PROP_62" => "-",
		"ADDITIONAL_PICT_PROP_63" => "-",
		"ALLOW_APPEND_ORDER" => "Y",
		"ALLOW_AUTO_REGISTER" => "Y",
		"ALLOW_NEW_PROFILE" => "Y",
		"ALLOW_USER_PROFILES" => "Y",
		"BASKET_IMAGES_SCALING" => "adaptive",
		"BASKET_POSITION" => "after",
		"COMPATIBLE_MODE" => "Y",
		"DELIVERIES_PER_PAGE" => "9",
		"DELIVERY_FADE_EXTRA_SERVICES" => "Y",
		"DELIVERY_NO_AJAX" => "Y",
		"DELIVERY_NO_SESSION" => "Y",
		"DELIVERY_TO_PAYSYSTEM" => "p2d",
		"DISABLE_BASKET_REDIRECT" => "Y",
		"EMPTY_BASKET_HINT_PATH" => "/",
		"HIDE_ORDER_DESCRIPTION" => "N",
		"ONLY_FULL_PAY_FROM_ACCOUNT" => "N",
		"ORDER_GROUP_PROPS" => "1",
		"ORDER_PROP_DELIVERY" => "",
		"PATH_TO_AUTH" => "/personal/profile/",
		"PATH_TO_BASKET" => "/personal/basket/",
		"PATH_TO_PAYMENT" => "/personal/basket/payment/",
		"PATH_TO_PERSONAL" => "/personal/profile/",
		"PAY_FROM_ACCOUNT" => "N",
		"PAY_SYSTEMS_PER_PAGE" => "9",
		"PICKUPS_PER_PAGE" => "5",
		"PICKUP_MAP_TYPE" => "yandex",
		"PRODUCT_COLUMNS_HIDDEN" => array("PREVIEW_PICTURE","DETAIL_PICTURE","PREVIEW_TEXT","PROPS","NOTES","DISCOUNT_PRICE_PERCENT_FORMATED","PRICE_FORMATED","WEIGHT_FORMATED"),
		"PRODUCT_COLUMNS_VISIBLE" => array("PREVIEW_PICTURE","PROPS","NOTES","DISCOUNT_PRICE_PERCENT_FORMATED","PRICE_FORMATED","WEIGHT_FORMATED"),
		"PROPS_FADE_LIST_1" => array("1","2","3","4","7"),
		"PROPS_FADE_LIST_2" => array("8","9","10","11","12","13","14","15","16","19"),
		"SEND_NEW_USER_NOTIFY" => "Y",
		"SERVICES_IMAGES_SCALING" => "adaptive",
		"SET_TITLE" => "Y",
		"SHOW_BASKET_HEADERS" => "Y",
		"SHOW_COUPONS" => "Y",
		"SHOW_COUPONS_BASKET" => "Y",
		"SHOW_COUPONS_DELIVERY" => "N",
		"SHOW_COUPONS_PAY_SYSTEM" => "N",
		"SHOW_DELIVERY_INFO_NAME" => "Y",
		"SHOW_DELIVERY_LIST_NAMES" => "Y",
		"SHOW_DELIVERY_PARENT_NAMES" => "Y",
		"SHOW_MAP_IN_PROPS" => "N",
		"SHOW_NEAREST_PICKUP" => "Y",
		"SHOW_NOT_CALCULATED_DELIVERIES" => "L",
		"SHOW_ORDER_BUTTON" => "final_step",
		"SHOW_PAY_SYSTEM_INFO_NAME" => "Y",
		"SHOW_PAY_SYSTEM_LIST_NAMES" => "Y",
		"SHOW_PICKUP_MAP" => "Y",
		"SHOW_STORES_IMAGES" => "Y",
		"SHOW_TOTAL_ORDER_BUTTON" => "Y",
		"SHOW_VAT_PRICE" => "Y",
		"SKIP_USELESS_BLOCK" => "N",
		"SPOT_LOCATION_BY_GEOIP" => "Y",
		"TEMPLATE_LOCATION" => "popup",
		"TEMPLATE_THEME" => "site",
		"USER_CONSENT" => "Y",
		"USER_CONSENT_ID" => "1",
		"USER_CONSENT_IS_CHECKED" => "Y",
		"USER_CONSENT_IS_LOADED" => "Y",
		"USE_CUSTOM_ADDITIONAL_MESSAGES" => "N",
		"USE_CUSTOM_ERROR_MESSAGES" => "N",
		"USE_CUSTOM_MAIN_MESSAGES" => "N",
		"USE_ENHANCED_ECOMMERCE" => "N",
		"USE_PHONE_NORMALIZATION" => "Y",
		"USE_PRELOAD" => "Y",
		"USE_PREPAYMENT" => "N",
		"USE_YM_GOALS" => "N"
	)
);?>

<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php") ?>